Prim and kruskal
monshinawatra/CSS113-project-tree pull request #2
Opened 2022-12-10 13:39 UTC by JackJessada

2022-12-10 13:40 UTC, JackJessada commented
Prim's algorithm

2022-12-10 15:55 UTC, monshinawatra requested changes
Overall, thanks to Prim's algorithm for finding the minimum spanning tree, I am looking forward to seeing the implementation of Kruskal's algorithm as well, as mentioned in the pull request name. I hope that it will be included in a future update. Thank you for your hard work and dedication to improving this project.

2022-12-10 15:55 UTC, monshinawatra commented on prim.py
> +while counter<len(all_vertex)-1:
Based on the information provided. It looks like you forgot to declare the `all_vertex` variable.

2022-12-10 15:55 UTC, monshinawatra commented on prim.py
> +    checklist=graph.vertices2name((graph.get_adjacent_vertices(first))) #ตัวที่Aพุ่งไปหาได้ ['B', 'C'] , check what vertex A can go
I know that `graph` is `Undirected Graph` but you forgot to declare the variable. I recommend declaring this on top of the file to avoid any potential issues or errors.

2022-12-10 15:55 UTC, monshinawatra commented on prim.py
> +        edge = (graph.get_edge_to(first, adj))
I have noticed that the code works as intended, but I'm unsure why you have included so many unnecessary parentheses in the code. In my opinion, removing these parentheses would improve the readability of the code and make it easier to understand. Is there a specific reason for including these parentheses, or could they be removed for the sake of clarity?

2022-12-10 15:55 UTC, monshinawatra commented on prim.py
> +print(f"anwser is {ans} and total weight is {sum(ans.values())}")
Misspelled. "anwser" should write as "answer".

2022-12-12 16:04 UTC, monshinawatra approved these changes

2022-12-12 16:04 UTC, merged